---
# Source: microservice/templates/xmicroservice.yaml
apiVersion: sparky.ee/v1alpha1
kind: XMicroservice
metadata:
  name: podinfo
  namespace: test1-1
  labels:
    platform.hooli.tech/stage: "test1-1"
    topology.kubernetes.io/zone: "eu-north-1b"
spec:
  image: "ghcr.io/stefanprodan/podinfo:6.14.1"
  replicas: 1
  port: 9898
  serviceType: ClusterIP
