apiVersion: platform.hooli.tech/v1alpha1
kind: XQueue
metadata:
  name: cncf-campinas-talk
  namespace: team-b
spec:
  location: US
  providerName: default
  visibilityTimeoutSeconds: 30
  maxMessageSize: 262144
  tags:
    foo: bar
